services:
  app-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-store
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
    depends_on:
      - db-store
    networks:
      - StoreOnline

  server-store:
    image: nginx:latest
    container_name: server-store
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-store
    networks:
      - StoreOnline

  db-store:
    image: mysql:8
    container_name: db-store
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - StoreOnline

volumes:
  dbdata:

networks:
  StoreOnline:
